Resources:
  TicketsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.TABLE_NAME}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
  AttachPreSignUpLambda:
    Type: AWS::Cognito::UserPoolLambdaAttachment
    Properties:
      UserPoolId: ${self:provider.environment.USER_POOL_ID}
      PreSignUp: !GetAtt PreSignUpLambdaFunction.Arn
  PermissionsPreSignUpLambdaInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PreSignUpLambdaFunction
      Action: lambda:InvokeFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: arn:aws:cognito-idp:${aws:region}:${aws:accountId}:userpool/${self:provider.environment.USER_POOL_ID}

